name: kanban
description: "A new Flutter project with Kanban board features."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+5

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc:
  equatable:
  shared_preferences:   
  hydrated_bloc:
  path_provider:
  json_serializable:
  dotted_border:
  kanban_board:
  drag_and_drop_lists:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/